// SPDX-License-Identifier: AGPL-3.0-only
// Copyright 2026-present the Unsloth AI Inc. team. All rights reserved. See /studio/LICENSE.AGPL-3.0

import { readFileSync } from "node:fs";
import { resolve } from "node:path";

const ROOT = resolve(import.meta.dirname, "..");

type Check = {
  file: string;
  includes?: string[];
  excludes?: string[];
};

type ScopedCheck = Check & {
  start: string;
  end?: string;
};

const checks: Check[] = [
  {
    file: "src/index.css",
    includes: [
      ".cognix-logo-mark",
      "transform: scale(1.04)",
      "html.dark .cognix-logo-mark",
      "invert(1) contrast(1.08)",
    ],
  },
  {
    file: "src/components/app-sidebar.tsx",
    includes: [
      'src="/cognix-logo.png"',
      "h-[31px] w-[31px]",
      "h-[24px] w-[24px]",
      "CogniX",
      "trainingAccessible",
      "cloudTrainingUnlocked",
      "showTrainingTools",
      "Local training needs an NVIDIA or AMD GPU.",
    ],
  },
  {
    file: "src/config/env.ts",
    includes: [
      "cloudTrainingUnlocked",
      "cloud_training_unlocked",
      "cloud_training_providers",
      "training_access",
      "training_local_available",
      "training_cloud_available",
      "trainingLocalAvailable",
      "trainingCloudAvailable",
      "isTrainingAccessible",
    ],
  },
  {
    file: "src/features/training/hooks/use-training-actions.ts",
    includes: [
      "cloudOnlyTraining",
      "platform.trainingCloudAvailable && !platform.trainingLocalAvailable",
      "prepareCloudTrainingHandoff",
      "buildCloudTrainingObjective",
      "buildCloudTrainingDataset",
      "preferredCloudTrainingTarget",
      "Mode CEO cloud training",
      "sans GPU local AMD/NVIDIA",
    ],
  },
  {
    file: "src/features/studio/sections/training-section.tsx",
    includes: [
      "cloudOnlyTraining",
      "trainingCloudAvailable && !s.trainingLocalAvailable",
      "formatCloudProviderLabel",
      "studio.training.prepareCloudTraining",
      "studio.training.cloudTrainingReady",
    ],
  },
  {
    file: "src/i18n/locales/en.ts",
    includes: [
      "prepareCloudTraining",
      "Prepare Cloud Training",
      "cloudTrainingReady",
      "CEO cloud training is available",
    ],
  },
  {
    file: "src/features/training/api/train-api.ts",
    includes: [
      "CloudTrainingHandoffRequest",
      "CloudTrainingHandoffResponse",
      "prepareCloudTrainingHandoff",
      '"/api/cognix/fine-tuning/cloud-handoff-plan"',
      "readyToExport",
    ],
  },
  {
    file: "src/app/routes/__root.tsx",
    includes: [
      "isChatOnlyAllowed(pathname: string, trainingAccessible = false)",
      'pathname === "/studio"',
      "platform.isTrainingAccessible()",
    ],
  },
  {
    file: "../backend/main.py",
    includes: [
      '"cloud_training_unlocked"',
      '"cloud_training_providers"',
      '"training_access"',
      '"cloud_ceo"',
      '"training_local_available"',
      '"training_cloud_available"',
      "CLOUD_TRAINING_PROVIDERS",
      "build_training_access_payload",
      "auth_storage.get_user_profile(subject)",
    ],
  },
  {
    file: "src/features/auth/components/auth-form.tsx",
    includes: [
      "cognix-auth-mode-pill",
      "Identifiant ou email",
      "Nom d'utilisateur",
      "Connexion",
      "Inscription",
      "fetchDeviceType({ force: true })",
    ],
    excludes: [
      "Se connecter a CogniX",
      "Se connecter à CogniX",
      "Log in to CogniX",
      "Setup your account",
      "Configurer votre compte",
    ],
  },
  {
    file: "src/features/chat/api/chat-api.ts",
    includes: [
      "CogniXContextPack",
      "CogniXExecutionPlan",
      "auditLogId",
      'CHAT_HISTORY_UPDATED_EVENT = "cognix-chat-history-updated"',
      'authFetch("/api/cognix/context/pack"',
      'authFetch("/api/cognix/orchestrator/plan"',
    ],
    excludes: [
      "unsloth-chat-history-updated",
    ],
  },
  {
    file: "src/features/chat/api/chat-adapter.ts",
    includes: [
      "buildCogniXContextPack",
      "buildLatestCogniXContextInstruction",
      "planCogniXExecution",
      "planLatestCogniXObjective",
      "willLoadModel",
      "willGenerate",
      "setLatestCogniXRoute",
    ],
    excludes: [
      "await classifyCogniXObjective",
    ],
  },
  {
    file: "src/features/chat/chat-page.tsx",
    includes: [
      "CogniX Auto",
      "latestRoute?.executionStatus",
      "Plan {latestRoute.planMode",
    ],
  },
  {
    file: "../backend/routes/cognix.py",
    includes: [
      '@router.post("/context/pack")',
      '@router.get("/context/graph/blueprint")',
      '@router.post("/context/graph/build")',
      '@router.get("/context/graph/snapshots")',
      '@router.post("/benchmark/run")',
      '@router.get("/benchmark/runs")',
      '@router.get("/admin/audit-logs")',
      '@router.get("/admin/benchmark-runs")',
      '@router.get("/tools/registry")',
      '@router.get("/tools/permission-matrix")',
      '@router.get("/tools/discovery/capabilities")',
      '@router.post("/tools/discovery/analyze")',
      '@router.get("/tools/recommendations")',
      '@router.post("/tools/recommendations/{recommendation_id}/ignore")',
      '@router.post("/tools/plan")',
      '@router.get("/models/packs")',
      '@router.post("/models/lifecycle-plan")',
      '@router.post("/models/cache/load-plan")',
      '@router.post("/thinking/plan")',
      '@router.post("/reflection/evaluate")',
      '@router.get("/reflection/evaluations")',
      '@router.get("/drafts/styles")',
      '@router.post("/drafts/plan")',
      '@router.get("/drafts/variants")',
      '@router.post("/drafts/variants")',
      '@router.get("/debate/roles")',
      '@router.post("/debate/plan")',
      '@router.get("/debate/sessions")',
      '@router.post("/debate/sessions/{session_id}/outputs")',
      '@router.get("/memory/blueprint")',
      '@router.post("/memory/plan")',
      '@router.get("/memory/skills/blueprint")',
      '@router.post("/memory/skills/candidates")',
      '@router.get("/memory/skills/candidates")',
      '@router.post("/memory/skills/candidates/{candidate_id}/approve")',
      '@router.post("/memory/skills/candidates/{candidate_id}/reject")',
      '@router.get("/memory/skills")',
      '@router.get("/memory/skills/export")',
      '@router.patch("/memory/skills/{memory_id}")',
      '@router.delete("/memory/skills/{memory_id}")',
      '@router.post("/memory/skills/injection-plan")',
      '@router.get("/workflows/blueprint")',
      '@router.get("/workflows/templates")',
      '@router.post("/workflows/record")',
      '@router.get("/workflows")',
      '@router.get("/workflows/{workflow_id}")',
      '@router.patch("/workflows/{workflow_id}")',
      '@router.delete("/workflows/{workflow_id}")',
      '@router.get("/workflows/{workflow_id}/export")',
      '@router.post("/workflows/{workflow_id}/run-plan")',
      '@router.get("/workflows/{workflow_id}/runs")',
      '@router.get("/prompt-compression/blueprint")',
      '@router.post("/prompt-compression/plan")',
      '@router.get("/prompt-compression/contexts")',
      '@router.get("/prompt-compression/contexts/{context_id}")',
      '@router.delete("/prompt-compression/contexts/{context_id}")',
      '@router.get("/intent/blueprint")',
      '@router.post("/intent/predict")',
      '@router.get("/intent/predictions")',
      '@router.get("/intent/preload-events")',
      '@router.get("/dynamic-ui/blueprint")',
      '@router.post("/dynamic-ui/profile")',
      '@router.get("/dynamic-ui/profiles")',
      '@router.get("/background-agents/blueprint")',
      '@router.post("/background-agents/job-plan")',
      '@router.get("/background-agents/jobs")',
      '@router.get("/background-agents/jobs/{job_id}")',
      '@router.get("/timeline/blueprint")',
      '@router.post("/timeline/events")',
      '@router.get("/timeline/events")',
      '@router.get("/research/watch-registry")',
      '@router.post("/research/integration-plan")',
      '@router.get("/integrations/status")',
      '@router.post("/integrations/plan")',
      '@router.get("/admin/permissions/{username}")',
      '@router.post("/admin/permissions/{username}")',
      '@router.delete("/admin/permissions/{username}/{permission_key}")',
      '@router.get("/admin/orchestrator-logs")',
      "context_pack_built",
      "context_graph_built",
      "rawHistoryAllowed",
      "tool_action_planned",
      "tool_discovery_analyzed",
      "tool_recommendation_ignored",
      "build_tool_permission_matrix",
      "integration_plan_built",
      "onboarding_plan_built",
      "deployment_plan_built",
      "governance_plan_built",
      "project_expert_plan_built",
      "model_lifecycle_plan_built",
      "cache_load_plan_built",
      "thinking_status_plan_built",
      "response_reflection_evaluated",
      "draft_generation_plan_built",
      "response_variant_stored",
      "debate_plan_built",
      "debate_output_stored",
      "memory_plan_built",
      "skill_memory_candidates_built",
      "skill_memory_candidate_approved",
      "skill_memory_candidate_rejected",
      "skill_memory_updated",
      "skill_memory_deleted",
      "skill_memory_exported",
      "skill_memory_injection_plan_built",
      "workflow_template_registry_built",
      "workflow_recording_built",
      "workflow_updated",
      "workflow_deleted",
      "workflow_exported",
      "workflow_run_plan_built",
      "prompt_compression_plan_built",
      "prompt_compression_context_deleted",
      "intent_prediction_built",
      "dynamic_ui_profile_built",
      "background_agent_job_planned",
      "timeline_event_planned",
      "research_integration_plan_built",
      "permission_granted",
      "permission_revoked",
      "rate_limited",
      "granted_permissions = _granted_permission_keys(current_subject)",
      "cognix_db.check_rate_limit",
      "cognix_db.create_orchestrator_log",
      '@router.post("/orchestrator/plan")',
      '@router.post("/codex/pipeline-plan")',
      '@router.get("/runtime/adapters")',
      '@router.post("/runtime/plan")',
      '@router.get("/modules/registry")',
      '@router.get("/modules/manifests")',
      '@router.post("/modules/plan")',
      '@router.get("/workers/registry")',
      '@router.post("/workers/plan")',
      '@router.post("/workers/job-spec-plan")',
      '@router.get("/optimizations/capabilities")',
      '@router.post("/optimizations/plan")',
      '@router.post("/optimizations/experiment-plan")',
      '@router.post("/models/preload-plan")',
      "build_cache_load_plan",
      '@router.post("/fine-tuning/plan")',
      '@router.post("/fine-tuning/cloud-handoff-plan")',
      '@router.get("/rag/sources")',
      '@router.post("/rag/indexing-plan")',
      '@router.post("/rag/plan")',
      '"orchestratorLogId"',
      '"latestBenchmark"',
      "get_latest_benchmark_run",
      '@router.post("/onboarding/plan")',
      '@router.get("/deployments/targets")',
      '@router.post("/deployments/plan")',
      '@router.get("/governance/blueprint")',
      '@router.post("/governance/plan")',
      '@router.get("/project-experts/registry")',
      '@router.post("/projects/{project_id}/expert-plan")',
      "preload_plan_built",
      "fine_tuning_plan_built",
      "fine_tuning_cloud_handoff_plan_built",
      "rag_source_registry_built",
      "rag_indexing_plan_built",
      "rag_plan_built",
      "module_manifest_bundle_built",
      "module_plan_built",
      "optimization_capability_registry_built",
      "optimization_plan_built",
      "optimization_experiment_plan_built",
      "runtime_adapter_plan_built",
      "codex_pipeline_plan_built",
      "worker_queue_registry_built",
      "worker_queue_plan_built",
      "worker_job_spec_plan_built",
      '"runtimeType": "dry_run"',
      '"runtimeError": None',
    ],
  },
  {
    file: "../backend/storage/cognix_db.py",
    includes: [
      "CREATE TABLE IF NOT EXISTS cognix_audit_logs",
      "AUDIT_LOG_RETENTION_LIMIT",
      "def create_audit_log",
      "def list_audit_logs",
      "def prune_audit_logs",
      "def grant_user_permission",
      "def revoke_user_permission",
      "def list_user_permissions",
      "CREATE TABLE IF NOT EXISTS cognix_rate_limit_events",
      "def check_rate_limit",
      "CREATE TABLE IF NOT EXISTS cognix_orchestrator_logs",
      "def create_orchestrator_log",
      "def list_orchestrator_logs",
      "CREATE TABLE IF NOT EXISTS cognix_benchmark_runs",
      "def create_benchmark_run",
      "def list_benchmark_runs",
      "def get_latest_benchmark_run",
      "CREATE TABLE IF NOT EXISTS cognix_response_evaluations",
      "def create_response_evaluation",
      "def list_response_evaluations",
      "CREATE TABLE IF NOT EXISTS cognix_response_variants",
      "def create_response_variant",
      "def list_response_variants",
      "CREATE TABLE IF NOT EXISTS cognix_debate_sessions",
      "CREATE TABLE IF NOT EXISTS cognix_debate_rounds",
      "CREATE TABLE IF NOT EXISTS cognix_debate_outputs",
      "def create_debate_session",
      "def list_debate_sessions",
      "def create_debate_output",
      "CREATE TABLE IF NOT EXISTS cognix_tool_recommendations",
      "CREATE TABLE IF NOT EXISTS cognix_installed_tools",
      "CREATE TABLE IF NOT EXISTS cognix_tool_capabilities",
      "def create_tool_recommendations",
      "def list_tool_recommendations",
      "def ignore_tool_recommendation",
      "def upsert_installed_tool",
      "def list_installed_tools",
      "CREATE TABLE IF NOT EXISTS cognix_context_nodes",
      "CREATE TABLE IF NOT EXISTS cognix_context_edges",
      "CREATE TABLE IF NOT EXISTS cognix_context_graph_snapshots",
      "def create_context_graph_snapshot",
      "def list_context_graph_snapshots",
      "def get_context_graph_snapshot",
      "CREATE TABLE IF NOT EXISTS cognix_memory_candidates",
      "CREATE TABLE IF NOT EXISTS cognix_user_skill_memories",
      "CREATE TABLE IF NOT EXISTS cognix_user_preferences",
      "def create_memory_candidates",
      "def list_memory_candidates",
      "def approve_memory_candidate",
      "def reject_memory_candidate",
      "def list_skill_memories",
      "def update_skill_memory",
      "def delete_skill_memory",
      "def export_skill_memory_bundle",
      "CREATE TABLE IF NOT EXISTS cognix_workflows",
      "CREATE TABLE IF NOT EXISTS cognix_workflow_steps",
      "CREATE TABLE IF NOT EXISTS cognix_workflow_runs",
      "CREATE TABLE IF NOT EXISTS cognix_workflow_run_logs",
      "def create_workflow_from_plan",
      "def list_workflows",
      "def get_workflow",
      "def update_workflow",
      "def delete_workflow",
      "def create_workflow_run_plan_record",
      "def list_workflow_runs",
      "def export_workflow_bundle",
      "CREATE TABLE IF NOT EXISTS cognix_compressed_contexts",
      "CREATE TABLE IF NOT EXISTS cognix_compression_logs",
      "def create_compressed_context",
      "def list_compressed_contexts",
      "def get_compressed_context",
      "def delete_compressed_context",
      "CREATE TABLE IF NOT EXISTS cognix_intent_predictions",
      "CREATE TABLE IF NOT EXISTS cognix_preload_events",
      "def create_intent_prediction",
      "def get_intent_prediction",
      "def list_intent_predictions",
      "def list_preload_events",
      "CREATE TABLE IF NOT EXISTS cognix_project_ui_profiles",
      "CREATE TABLE IF NOT EXISTS cognix_user_layout_preferences",
      "def create_project_ui_profile",
      "def get_project_ui_profile",
      "def list_project_ui_profiles",
      "CREATE TABLE IF NOT EXISTS cognix_background_jobs",
      "CREATE TABLE IF NOT EXISTS cognix_background_agent_runs",
      "CREATE TABLE IF NOT EXISTS cognix_background_job_logs",
      "def create_background_job_from_plan",
      "def get_background_job",
      "def list_background_jobs",
      "CREATE TABLE IF NOT EXISTS cognix_project_timeline_events",
      "def create_timeline_event",
      "def list_timeline_events",
      "metadata_json",
      "evaluation_json",
    ],
  },
  {
    file: "../backend/core/cognix/benchmark.py",
    includes: [
      'COGNIX_BENCHMARK_VERSION = "cognix_benchmark_v1"',
      "def run_benchmark",
      '"estimatedTokensPerSecond"',
      '"modelFitness"',
      '"optimizationPlan"',
      '"networkCall": False',
      '"gpuStressTest": False',
    ],
  },
  {
    file: "../backend/core/cognix/decision_engine.py",
    includes: [
      'COGNIX_DECISION_ENGINE_VERSION = "cognix_decision_engine_v1"',
      "def build_task_strategy",
      '"rag_first"',
      '"guided_fine_tuning"',
      '"codex_guarded_pipeline"',
      '"toolExecution": False',
      '"fineTuningJob": False',
    ],
  },
  {
    file: "../backend/core/cognix/context_manager.py",
    includes: [
      'CONTEXT_MANAGER_VERSION = "cognix_context_manager_v1"',
      "def build_context_plan",
      '"systemInstruction"',
      '"contextPlan"',
      '"assemblyStrategy"',
      '"rawHistoryAllowed": False',
      '"never_send_raw_history"',
      '"user_memory"',
      '"project_instructions"',
      '"rag_chunks"',
      '"memoryWrite": False',
      '"ragRetrieval": False',
      '"networkModelCall": False',
    ],
  },
  {
    file: "../backend/core/cognix/memory_manager.py",
    includes: [
      'COGNIX_MEMORY_MANAGER_VERSION = "cognix_memory_manager_v1"',
      "def build_memory_blueprint",
      "def build_memory_plan",
      '"user_memory"',
      '"project_memory"',
      '"conversation_summary"',
      '"document_memory"',
      '"organization_memory"',
      '"technical_memory"',
      '"memoryIsModelIndependent": True',
      '"rawConversationHistoryDisallowedByDefault": True',
      '"frontendDirectMemoryMutationAllowed": False',
      '"rawHistoryAllowed": False',
      '"memoryScopesIsolated": True',
      '"memoryWrite": False',
      '"summaryWrite": False',
      '"documentRetrieval": False',
      '"ragIndexing": False',
      '"technicalProfileWrite": False',
      '"modelLoad": False',
      '"generation": False',
    ],
  },
  {
    file: "../backend/core/cognix/skill_memory.py",
    includes: [
      'COGNIX_SKILL_MEMORY_VERSION = "cognix_skill_memory_v1"',
      'COGNIX_PREFERENCE_EXTRACTOR_VERSION = "cognix_preference_extractor_v1"',
      'COGNIX_MEMORY_APPROVAL_VERSION = "cognix_memory_approval_v1"',
      'COGNIX_CONTEXT_INJECTOR_VERSION = "cognix_context_injector_v1"',
      "def build_skill_memory_blueprint",
      "def build_candidate_memory_plan",
      "def build_context_injection_plan",
      '"approveBeforeActivation": True',
      '"automaticApprovalAllowed": False',
      '"contextInjectionOnlyWhenRelevant": True',
      '"rawObservationInjectionAllowed": False',
      '"requiresUserApproval": True',
      '"canAutoApprove": False',
      '"memoryCandidateWrite": False',
      '"skillMemoryWrite": False',
      '"preferenceWrite": False',
      '"contextInjection": False',
      '"modelLoad": False',
      '"generation": False',
    ],
  },
  {
    file: "../backend/core/cognix/workflow_recorder.py",
    includes: [
      'COGNIX_WORKFLOW_RECORDER_VERSION = "cognix_workflow_recorder_v1"',
      'COGNIX_WORKFLOW_RUNNER_VERSION = "cognix_workflow_runner_v1"',
      'COGNIX_WORKFLOW_TEMPLATE_MANAGER_VERSION = "cognix_workflow_template_manager_v1"',
      "WorkflowRecorder",
      "WorkflowRunner",
      "WorkflowTemplateManager",
      "def build_workflow_blueprint",
      "def build_workflow_template_registry",
      "def build_workflow_recording_plan",
      "def build_workflow_run_plan",
      '"rag_workflow"',
      '"fine_tuning_workflow"',
      '"code_workflow"',
      '"document_workflow"',
      '"dryRunByDefault": True',
      '"executeWithoutUserConfirmation": False',
      '"frontendDirectToolExecutionAllowed": False',
      '"frontendDirectModelCallAllowed": False',
      '"rawSecretCaptureAllowed": False',
      '"workflowWrite": False',
      '"workflowRunWrite": False',
      '"toolExecution": False',
      '"modelLoad": False',
      '"generation": False',
      '"exportWrite": False',
      '"networkCall": False',
    ],
  },
  {
    file: "../backend/core/cognix/prompt_compression.py",
    includes: [
      'COGNIX_PROMPT_COMPRESSION_VERSION = "cognix_prompt_compression_v1"',
      'COGNIX_CONTEXT_RANKER_VERSION = "cognix_context_ranker_v1"',
      'COGNIX_COMPRESSION_EVALUATOR_VERSION = "cognix_compression_evaluator_v1"',
      "PromptCompressionService",
      "ContextRanker",
      "CompressionEvaluator",
      "def estimate_tokens",
      "def build_prompt_compression_blueprint",
      "def build_prompt_compression_plan",
      "def build_compression_evaluation",
      '"Context optimized"',
      '"importance_ranking"',
      '"compressed_summary"',
      '"optional_validation"',
      '"modelGenerationAllowed": False',
      '"frontendDirectCompressionWriteAllowed": False',
      '"compressionWrite": False',
      '"logWrite": False',
      '"modelLoad": False',
      '"generation": False',
      '"networkCall": False',
      '"promptMutation": False',
    ],
  },
  {
    file: "../backend/core/cognix/intent_prediction.py",
    includes: [
      'COGNIX_INTENT_PREDICTION_VERSION = "cognix_intent_prediction_v1"',
      'COGNIX_PRELOAD_SCHEDULER_VERSION = "cognix_preload_scheduler_v1"',
      "IntentPredictionService",
      "PreloadScheduler",
      "ModelCacheManager",
      "def build_intent_prediction_blueprint",
      "def build_intent_prediction",
      '"mostlyInvisible": True',
      '"maxSuggestions": 1',
      '"actualPreloadAllowedHere": False',
      '"abruptDomainChangeThreshold"',
      '"predictionWrite": False',
      '"preloadEventWrite": False',
      '"modelLoad": False',
      '"modelUnload": False',
      '"generation": False',
      '"networkCall": False',
      '"uiSuggestion": False',
    ],
  },
  {
    file: "../backend/core/cognix/dynamic_ui.py",
    includes: [
      'COGNIX_DYNAMIC_UI_VERSION = "cognix_dynamic_ui_v1"',
      'COGNIX_UI_LAYOUT_PROFILE_VERSION = "cognix_ui_layout_profile_v1"',
      "UILayoutProfileManager",
      "ProjectLayoutRenderer",
      "AdaptivePanels",
      "def build_dynamic_ui_blueprint",
      "def build_project_ui_profile",
      '"sameDesignSystem": True',
      '"sameTypography": True',
      '"sameNavigationLogic": True',
      '"noVisualRupture": True',
      '"mobileDesktopAware": True',
      '"files", "editor", "terminal", "tests"',
      '"latex-renderer", "formula-table"',
      '"profileWrite": False',
      '"uiMutation": False',
      '"routeMutation": False',
      '"themeMutation": False',
      '"toolExecution": False',
      '"modelLoad": False',
      '"generation": False',
    ],
  },
  {
    file: "../backend/core/cognix/background_agents.py",
    includes: [
      'COGNIX_BACKGROUND_AGENT_VERSION = "cognix_background_agent_v1"',
      'COGNIX_PROGRESS_TRACKER_VERSION = "cognix_progress_tracker_v1"',
      'COGNIX_NOTIFICATION_PLAN_VERSION = "cognix_notification_plan_v1"',
      "BackgroundAgentService",
      "JobQueue",
      "ProgressTracker",
      "NotificationService",
      "def build_background_agent_blueprint",
      "def build_background_agent_job_plan",
      '"queueRequired": True',
      '"nightModeRespected": True',
      '"directToolExecutionAllowed": False',
      '"jobEnqueue": False',
      '"agentRunWrite": False',
      '"progressLogWrite": False',
      '"workerStart": False',
      '"toolExecution": False',
      '"modelLoad": False',
      '"generation": False',
      '"notificationSend": False',
    ],
  },
  {
    file: "../backend/core/cognix/timeline.py",
    includes: [
      'COGNIX_TIMELINE_VERSION = "cognix_timeline_v1"',
      'COGNIX_TIMELINE_EVENT_CLASSIFIER_VERSION = "cognix_timeline_event_classifier_v1"',
      "TimelineService",
      "EventClassifier",
      "ProjectHistoryStore",
      "def build_timeline_blueprint",
      "def build_timeline_event_plan",
      "def classify_timeline_event",
      '"Timeline"',
      '"elegantHistory": True',
      '"rawLogUi": False',
      '"clickableEvents": True',
      '"timelineWrite": False',
      '"uiMutation": False',
      '"modelLoad": False',
      '"generation": False',
      '"toolExecution": False',
    ],
  },
  {
    file: "../backend/core/cognix/tool_registry.py",
    includes: [
      'TOOL_REGISTRY_VERSION = "cognix_tool_registry_v1"',
      "frontendDirectExecutionAllowed",
      "permissionMatrixAvailable",
      "RATE_LIMIT_POLICIES",
      "rate_limit_policy_for_key",
      "build_tool_permission_matrix",
      "permission_matrix_dry_run",
      "permissionContext",
      "guardrails",
      '"secretRead": False',
      '"permissionWrite": False',
      "requiresConfirmation",
      "auditRequired",
      "sandboxRequired",
      '"toolExecution": False',
      "def plan_tool_action",
    ],
  },
  {
    file: "../backend/core/cognix/tool_discovery.py",
    includes: [
      'COGNIX_TOOL_DISCOVERY_VERSION = "cognix_tool_discovery_v1"',
      'COGNIX_TOOL_CAPABILITY_REGISTRY_VERSION = "cognix_tool_capability_registry_v1"',
      "DISCOVERABLE_TOOL_CAPABILITIES",
      "PROJECT_NEED_RULES",
      "def build_tool_capability_registry",
      "def build_tool_discovery_plan",
      '"automaticInstallationAllowed": False',
      '"frontendDirectInstallationAllowed": False',
      '"installation": False',
      '"toolExecution": False',
      '"networkToolCall": False',
      '"secretRead": False',
      '"latex-renderer"',
      '"python-runtime"',
      '"ollama"',
      '"llama-cpp"',
      '"google-workspace"',
      '"microsoft-365"',
    ],
  },
  {
    file: "../backend/core/cognix/context_graph.py",
    includes: [
      'COGNIX_CONTEXT_GRAPH_VERSION = "cognix_context_graph_v1"',
      'COGNIX_ENTITY_EXTRACTOR_VERSION = "cognix_entity_extractor_v1"',
      'COGNIX_RELATION_BUILDER_VERSION = "cognix_relation_builder_v1"',
      "def build_context_graph_blueprint",
      "def build_context_graph_snapshot",
      '"projectTabCompatible": True',
      '"themeAwareTokensOnly": True',
      '"customVisualizationLibraryRequired": False',
      '"rawConversationContentVisibleByDefault": False',
      '"rawMessageContentStoredInGraph": False',
      '"modelGenerationAllowed": False',
      '"externalRetrievalAllowed": False',
      '"generation": False',
      '"toolExecution": False',
      '"snapshotWrite": False',
      '"uiMutation": False',
    ],
  },
  {
    file: "../backend/core/cognix/module_registry.py",
    includes: [
      'COGNIX_MODULE_REGISTRY_VERSION = "cognix_module_registry_v1"',
      'COGNIX_MODULE_MANIFEST_SCHEMA_VERSION = "cognix_module_manifest_schema_v1"',
      'COGNIX_MODULE_MANIFEST_BUNDLE_VERSION = "cognix_module_manifest_bundle_v1"',
      "def build_module_registry",
      "def build_module_manifest_bundle",
      "def build_module_activation_plan",
      '"cognix-onboarding"',
      '"cognix-model-lifecycle"',
      '"cognix-optimization-engine"',
      '"cognix-prompt-compression"',
      '"cognix-intent-prediction"',
      '"cognix-dynamic-ui"',
      '"cognix-background-agents"',
      '"cognix-ai-timeline"',
      '"cognix-thinking-status"',
      '"cognix-response-reflection"',
      '"cognix-multi-draft-generation"',
      '"cognix-ai-debate"',
      '"cognix-tool-discovery"',
      '"cognix-context-graph"',
      '"cognix-memory-manager"',
      '"cognix-long-term-skill-memory"',
      '"cognix-ai-workflow-recorder"',
      '"cognix-research-watch"',
      '"cognix-deployment-manager"',
      '"cognix-worker-queue"',
      '"cloud_training_targets"',
      '"cloud_training_handoff"',
      '"worker_job_specs"',
      '"cloud_training_job_specs"',
      '"optimization_capability_registry"',
      '"benchmark_gated_experiments"',
      '"ceo_cloud_training_bypass"',
      '"rag_source_registry"',
      '"rag_indexing_planning"',
      '"technology_watch"',
      '"benchmark_gate"',
      '"tool_permission_matrix"',
      '"load_unload_planning"',
      '"cache_load_planning"',
      '"module_manifest_registry"',
      '"technical_redaction"',
      '"response_quality_evaluation"',
      '"confidence_scoring"',
      '"raw_reasoning_redaction"',
      '"style_profile_registry"',
      '"multi_draft_planning"',
      '"response_variant_store"',
      '"debate_role_registry"',
      '"bounded_debate_planning"',
      '"judge_synthesis_planning"',
      '"public_argument_summaries"',
      '"project_tool_need_detection"',
      '"tool_capability_registry"',
      '"tool_recommendation_store"',
      '"installed_tool_snapshot"',
      '"no_auto_install_guardrail"',
      '"context_graph_snapshot"',
      '"entity_extraction"',
      '"relation_builder"',
      '"graph_store"',
      '"project_context_map"',
      '"central_memory_layers"',
      '"skill_memory_candidates"',
      '"preference_extraction"',
      '"memory_approval_flow"',
      '"user_memory_controls"',
      '"context_injection_planning"',
      '"workflow_recording"',
      '"workflow_steps_store"',
      '"workflow_replay_planning"',
      '"workflow_template_registry"',
      '"workflow_export"',
      '"workflow_sharing_controls"',
      '"prompt_compression"',
      '"importance_ranking"',
      '"compressed_context_store"',
      '"compression_evaluation"',
      '"context_optimized_badge"',
      '"intent_prediction"',
      '"domain_probability"',
      '"preload_planning"',
      '"single_useful_suggestion"',
      '"abrupt_domain_change_detection"',
      '"ui_layout_profiles"',
      '"adaptive_panels"',
      '"project_type_layout_mapping"',
      '"theme_safe_layout_planning"',
      '"mobile_desktop_layout_planning"',
      '"background_job_planning"',
      '"agent_queue_contract"',
      '"progress_tracking"',
      '"notification_planning"',
      '"night_mode_respect"',
      '"project_timeline_events"',
      '"timeline_event_classification"',
      '"project_history_store"',
      '"timeline_filtering"',
      '"timeline_search"',
      '"/api/cognix/modules/manifests"',
      '"/api/cognix/models/lifecycle-plan"',
      '"/api/cognix/models/cache/load-plan"',
      '"/api/cognix/optimizations/capabilities"',
      '"/api/cognix/optimizations/experiment-plan"',
      '"/api/cognix/reflection/evaluate"',
      '"/api/cognix/reflection/evaluations"',
      '"/api/cognix/drafts/styles"',
      '"/api/cognix/drafts/plan"',
      '"/api/cognix/drafts/variants"',
      '"/api/cognix/debate/roles"',
      '"/api/cognix/debate/plan"',
      '"/api/cognix/debate/sessions"',
      '"/api/cognix/tools/discovery/capabilities"',
      '"/api/cognix/tools/discovery/analyze"',
      '"/api/cognix/tools/recommendations"',
      '"/api/cognix/context/graph/blueprint"',
      '"/api/cognix/context/graph/build"',
      '"/api/cognix/context/graph/snapshots"',
      '"/api/cognix/fine-tuning/cloud-handoff-plan"',
      '"/api/cognix/workers/registry"',
      '"/api/cognix/workers/job-spec-plan"',
      '"/api/cognix/thinking/plan"',
      '"/api/cognix/memory/plan"',
      '"/api/cognix/memory/skills/candidates"',
      '"/api/cognix/memory/skills/export"',
      '"/api/cognix/memory/skills/injection-plan"',
      '"/api/cognix/workflows/record"',
      '"/api/cognix/workflows/{workflow_id}/export"',
      '"/api/cognix/workflows/{workflow_id}/run-plan"',
      '"/api/cognix/prompt-compression/plan"',
      '"/api/cognix/prompt-compression/contexts"',
      '"/api/cognix/intent/predict"',
      '"/api/cognix/intent/preload-events"',
      '"/api/cognix/dynamic-ui/profile"',
      '"/api/cognix/background-agents/job-plan"',
      '"/api/cognix/timeline/events"',
      '"/api/cognix/research/integration-plan"',
      '"/api/cognix/rag/sources"',
      '"/api/cognix/rag/indexing-plan"',
      '"/api/cognix/tools/permission-matrix"',
      '"project_expert_routing"',
      '"/api/cognix/project-experts/registry"',
      '"sso_planning"',
      '"/api/cognix/governance/plan"',
      '"declarativeManifestRequired": True',
      '"frontendCannotSelfRegisterModules": True',
      '"runtimeRouteMutationAllowed": False',
      '"frontendSelfRegistrationAllowed": False',
      '"manifestValidation"',
      '"moduleActivation": False',
      '"routeRegistration": False',
      '"uiMutation": False',
      '"permissionWrite": False',
      '"toolExecution": False',
      '"secretRead": False',
    ],
  },
  {
    file: "../backend/core/cognix/integration_manager.py",
    includes: [
      'COGNIX_INTEGRATION_MANAGER_VERSION = "cognix_integration_manager_v1"',
      "def build_integration_status",
      "def build_integration_plan",
      '"secretsStayServerSide": True',
      '"directFrontendExecutionAllowed": False',
      '"integrationActivation": False',
      '"secretRead": False',
      '"toolExecution": False',
      '"networkToolCall": False',
    ],
  },
  {
    file: "../backend/core/cognix/cache_manager.py",
    includes: [
      'MODEL_CACHE_MANAGER_VERSION = "model_cache_manager_v1"',
      "def build_cache_state",
      "def build_cache_load_plan",
      "would_unload_before_load",
      "would_load_model",
      "active_last_resort",
      '"modelLoad": False',
      '"modelUnload": False',
      '"cacheMutation": False',
      '"runtimeMutation": False',
    ],
  },
  {
    file: "../backend/core/cognix/optimization_planner.py",
    includes: [
      'COGNIX_OPTIMIZATION_PLANNER_VERSION = "cognix_optimization_planner_v1"',
      'COGNIX_OPTIMIZATION_CAPABILITY_REGISTRY_VERSION = "cognix_optimization_capability_registry_v1"',
      'COGNIX_OPTIMIZATION_EXPERIMENT_PLAN_VERSION = "cognix_optimization_experiment_plan_v1"',
      "OPTIMIZATION_CAPABILITIES",
      "def build_optimization_plan",
      "def build_optimization_capability_registry",
      "def build_optimization_experiment_plan",
      '"quantization_profile"',
      '"prompt_cache"',
      '"kv_cache_policy"',
      '"semantic_cache"',
      '"kv_cache_eviction"',
      '"flash_attention"',
      '"rag_compression"',
      '"speculative_decoding"',
      '"benchmarkRequiredBeforeEnable"',
      '"frontendDirectOptimizationMutationAllowed": False',
      '"modelReconfiguration": False',
      '"cacheMutation": False',
      '"benchmarkRun": False',
    ],
  },
  {
    file: "../backend/core/cognix/onboarding.py",
    includes: [
      'COGNIX_ONBOARDING_VERSION = "cognix_onboarding_v1"',
      "def build_onboarding_plan",
      '"hardwareSummary"',
      '"recommendedPack"',
      '"blockedModels"',
      '"firstSteps"',
      '"run_local_benchmark"',
      '"prepare_document_memory"',
      '"create_code_project"',
      '"profileWrite": False',
      '"settingsWrite": False',
      '"modelDownload": False',
      '"modelLoad": False',
      '"benchmarkRun": False',
      '"ragIndexing": False',
    ],
  },
  {
    file: "../backend/core/cognix/deployment_manager.py",
    includes: [
      'COGNIX_DEPLOYMENT_MANAGER_VERSION = "cognix_deployment_manager_v1"',
      "def build_deployment_target_registry",
      "def build_deployment_plan",
      '"on_prem_single_gpu"',
      '"on_prem_multi_gpu"',
      '"cloud_managed"',
      '"gpuScheduler"',
      '"autoscaling"',
      '"moeServing"',
      '"productionDeploymentFromPlannerAllowed": False',
      '"deployment": False',
      '"infrastructureProvisioning": False',
      '"serverStart": False',
      '"containerStart": False',
      '"dnsChange": False',
      '"secretWrite": False',
      '"networkExposure": False',
    ],
  },
  {
    file: "../backend/core/cognix/governance_manager.py",
    includes: [
      'COGNIX_GOVERNANCE_MANAGER_VERSION = "cognix_governance_manager_v1"',
      "def build_governance_blueprint",
      "def build_governance_plan",
      '"owner"',
      '"teacher"',
      '"student"',
      '"microsoft_entra_id"',
      '"google_workspace"',
      '"organizations"',
      '"rbac"',
      '"sso"',
      '"education_spaces"',
      '"class_permissions"',
      '"frontendCannotGrantRoles": True',
      '"organizationWrite": False',
      '"roleGrant": False',
      '"permissionWrite": False',
      '"ssoMutation": False',
      '"secretRead": False',
      '"secretWrite": False',
      '"directorySync": False',
      '"classroomWrite": False',
      '"policyActivation": False',
    ],
  },
  {
    file: "../backend/core/cognix/project_experts.py",
    includes: [
      'COGNIX_PROJECT_EXPERTS_VERSION = "cognix_project_experts_v1"',
      "def build_project_expert_registry",
      "def build_project_expert_plan",
      '"cognix-code"',
      '"cognix-maths"',
      '"cognix-physique"',
      '"cognix-general"',
      '"generalistVerifier"',
      '"direct_expert_for_specialized_project"',
      '"specializedProjectsPreferPrimaryExpert": True',
      '"frontendCannotLoadExpertDirectly": True',
      '"modelLoad": False',
      '"projectMutation": False',
      '"defaultModelWrite": False',
      '"cacheMutation": False',
      '"ragRetrieval": False',
      '"memoryWrite": False',
    ],
  },
  {
    file: "../backend/core/cognix/model_lifecycle.py",
    includes: [
      'COGNIX_MODEL_LIFECYCLE_VERSION = "cognix_model_lifecycle_v1"',
      "def build_model_pack_registry",
      "def build_model_lifecycle_plan",
      '"cognix-code-local"',
      '"ollama-qwen-4b-local"',
      '"glm-700b"',
      '"frontendCannotDownloadModels": True',
      '"frontendCannotLoadModelsDirectly": True',
      '"modelDownload": False',
      '"modelInstall": False',
      '"modelLoad": False',
      '"modelUnload": False',
      '"runtimeMutation": False',
      '"cacheMutation": False',
      '"networkCall": False',
      '"generation": False',
      '"settingsWrite": False',
      '"fileWrite": False',
    ],
  },
  {
    file: "../backend/core/cognix/thinking_status.py",
    includes: [
      'COGNIX_THINKING_STATUS_VERSION = "cognix_thinking_status_v1"',
      "def build_thinking_status_plan",
      '"visibleTimeline"',
      '"currentMessage"',
      '"frontendMustHideRawRoutingScores": True',
      '"frontendMustHideModelIdentifiers": True',
      '"visibleTimelineContainsModelIds": False',
      '"visibleTimelineContainsRoutingScores": False',
      '"visibleTimelineContainsRawHistory": False',
      '"modelLoad": False',
      '"generation": False',
      '"networkModelCall": False',
      '"cacheMutation": False',
      '"memoryWrite": False',
      '"ragRetrieval": False',
      '"uiMutation": False',
    ],
  },
  {
    file: "../backend/core/cognix/response_reflection.py",
    includes: [
      'COGNIX_RESPONSE_REFLECTION_VERSION = "cognix_response_reflection_v1"',
      "def build_response_reflection_evaluation",
      '"confidence"',
      '"verificationRequired"',
      '"recommendedAction"',
      '"rawChainOfThoughtAllowed": False',
      '"frontendMustNotShowHiddenReasoning": True',
      '"modelLoad": False',
      '"generation": False',
      '"networkModelCall": False',
      '"toolExecution": False',
      '"rawReasoningExposure": False',
    ],
  },
  {
    file: "../backend/core/cognix/draft_generation.py",
    includes: [
      'COGNIX_DRAFT_GENERATION_VERSION = "cognix_draft_generation_v1"',
      'COGNIX_STYLE_PROFILE_REGISTRY_VERSION = "cognix_style_profile_registry_v1"',
      "STYLE_PROFILES",
      "def build_style_profile_registry",
      "def build_draft_generation_plan",
      '"quick"',
      '"detailed"',
      '"technical"',
      '"simple"',
      '"business"',
      '"pedagogical"',
      '"backendOrchestratorRequired": True',
      '"frontendDirectModelCallAllowed": False',
      '"multipleDraftsOnDemandOnly": True',
      '"modelLoad": False',
      '"generation": False',
      '"networkModelCall": False',
      '"variantWrite": False',
    ],
  },
  {
    file: "../backend/core/cognix/debate_orchestrator.py",
    includes: [
      'COGNIX_DEBATE_ORCHESTRATOR_VERSION = "cognix_debate_orchestrator_v1"',
      'COGNIX_DEBATE_ROLE_REGISTRY_VERSION = "cognix_debate_role_registry_v1"',
      "ROLE_PROFILES",
      "def build_debate_role_registry",
      "def build_debate_plan",
      '"advocate"',
      '"critic"',
      '"synthesizer"',
      '"backendOrchestratorRequired": True',
      '"rawChainOfThoughtAllowed": False',
      '"publicArgumentsOnly": True',
      '"judgeSynthesisRequired": True',
      '"rawChainOfThoughtVisible": False',
      '"modelLoad": False',
      '"generation": False',
      '"networkModelCall": False',
      '"debateSessionWrite": False',
      '"debateOutputWrite": False',
    ],
  },
  {
    file: "../backend/core/cognix/runtime_adapter.py",
    includes: [
      'COGNIX_RUNTIME_ADAPTER_VERSION = "cognix_runtime_adapter_v1"',
      "def build_runtime_adapter_registry",
      "def build_runtime_adapter_plan",
      '"llama.cpp"',
      '"vllm"',
      '"transformers"',
      '"frontendMustUseBackend": True',
      '"runtimeMutation": False',
      '"serverStart": False',
      '"networkModelCall": False',
    ],
  },
  {
    file: "../backend/core/cognix/codex_pipeline.py",
    includes: [
      'COGNIX_CODEX_PIPELINE_VERSION = "cognix_codex_pipeline_v1"',
      "def build_codex_pipeline_plan",
      '"create_git_branch"',
      '"modify_native_source"',
      '"run_tests"',
      '"run_build"',
      '"human_approval"',
      '"branchCreate": False',
      '"fileWrite": False',
      '"codeModification": False',
      '"merge": False',
      '"deployment": False',
    ],
  },
  {
    file: "../backend/core/cognix/worker_queue.py",
    includes: [
      'COGNIX_WORKER_QUEUE_VERSION = "cognix_worker_queue_v1"',
      'COGNIX_WORKER_JOB_SPEC_VERSION = "cognix_worker_job_spec_v1"',
      "def build_worker_queue_registry",
      "def build_worker_queue_plan",
      "def build_worker_job_spec_plan",
      '"rag_indexing"',
      '"fine_tuning_job"',
      '"cloud_training"',
      '"cloud_training_job"',
      '"codex_pipeline"',
      '"model_preload"',
      '"benchmark_run"',
      '"idempotencyKeyRequired": True',
      '"rawPayloadStorageAllowed": False',
      '"frontendDirectQueueMutationAllowed": False',
      '"jobEnqueue": False',
      '"workerStart": False',
      '"cloudTrainingJob": False',
      '"fineTuningJob": False',
      '"codeModification": False',
      '"deployment": False',
    ],
  },
  {
    file: "../backend/core/cognix/orchestrator.py",
    includes: [
      '"orchestratorVersion": "cognix_orchestrator_v1"',
      '"mode": "dry_run"',
      "latest_benchmark_run",
      "cognix_security_policy.build_execution_policy",
      "cognix_codex_pipeline.build_codex_pipeline_plan",
      "cognix_context_manager.build_context_plan",
      "cognix_optimization_planner.build_optimization_plan",
      "cognix_runtime_adapter.build_runtime_adapter_plan",
      "cognix_preload_planner.build_preload_plan",
      "cognix_project_experts.build_project_expert_plan",
      "cognix_fine_tuning_planner.build_fine_tuning_plan",
      "user_plan",
      "cognix_rag_planner.build_rag_plan",
      "cognix_worker_queue.build_worker_queue_plan",
      '"executionPolicy"',
      '"codexPipelinePlan"',
      '"workerQueuePlan"',
      '"ragPlan"',
      '"contextPlan"',
      '"optimizationPlan"',
      '"runtimeAdapterPlan"',
      '"preloadPlan"',
      '"projectExpertPlan"',
      '"fineTuningPlan"',
      '"plan_rag"',
      '"plan_codex_pipeline"',
      '"plan_context"',
      '"plan_optimizations"',
      '"select_runtime_adapter"',
      '"plan_preload"',
      '"plan_project_expert"',
      '"plan_fine_tuning"',
      '"plan_worker_queue"',
      '"ragReadyForRetrieval"',
      '"ragStrategy"',
      '"contextAssemblyStrategy"',
      '"rawHistoryAllowed"',
      '"optimizationProfile"',
      '"runtimeAdapterId"',
      '"projectExpertId"',
      '"generalistVerifierEnabled"',
      '"codexPipelineApplicable"',
      '"codexBranchName"',
      '"workerQueueRecommended"',
      '"plannedWorkerJobCount"',
      '"preloadAction"',
      '"fineTuningMethod"',
      '"automaticExecutionAllowed"',
      "cognix_decision_engine.build_task_strategy",
      '"taskStrategy"',
      '"latestBenchmark"',
      '"recommendedPath"',
      '"willLoadModel": False',
      '"willGenerate": False',
      '"networkModelCall": False',
      '"projectMutation": False',
      '"defaultModelWrite": False',
      '"jobEnqueue": False',
      '"workerStart": False',
    ],
  },
  {
    file: "../backend/core/cognix/security_policy.py",
    includes: [
      'COGNIX_SECURITY_POLICY_VERSION = "cognix_security_policy_v1"',
      "def build_execution_policy",
      '"dry_run_guarded"',
      '"automaticExecutionAllowed": False',
      '"frontendDirectModelCallAllowed": False',
      '"frontendDirectToolExecutionAllowed": False',
      '"deniedSideEffects"',
    ],
  },
  {
    file: "../backend/core/cognix/preload_planner.py",
    includes: [
      'COGNIX_PRELOAD_PLANNER_VERSION = "cognix_preload_planner_v1"',
      "def build_preload_plan",
      '"observe_only"',
      '"would_preload"',
      '"would_preload_after_lru"',
      '"defer_preload"',
      '"cacheMutation": False',
    ],
  },
  {
    file: "../backend/core/cognix/fine_tuning_planner.py",
    includes: [
      'COGNIX_FINE_TUNING_PLANNER_VERSION = "cognix_fine_tuning_planner_v1"',
      "def build_fine_tuning_plan",
      "def build_cloud_training_handoff_plan",
      '"cognix_cloud_training_handoff_v1"',
      '"rag_before_fine_tuning"',
      '"guided_fine_tuning"',
      '"qlora"',
      '"cloud_qlora"',
      '"google_colab"',
      '"kaggle"',
      '"kaggle_kernel_plan"',
      '"cloud_training_job"',
      '"localGpuBypassAllowed"',
      '"notebookWrite": False',
      '"datasetUpload": False',
      '"networkCall": False',
      '"datasetImport": False',
      '"fineTuningJob": False',
      '"cloudTrainingJob": False',
      '"cloudCredentialRead": False',
      '"adapterWrite": False',
    ],
  },
  {
    file: "../backend/core/cognix/research_watch.py",
    includes: [
      'COGNIX_RESEARCH_WATCH_VERSION = "cognix_research_watch_v1"',
      "def build_research_watch_registry",
      "def build_research_integration_plan",
      '"DeepSeek"',
      '"Anthropic"',
      '"Google / Google DeepMind"',
      '"Sakana AI"',
      '"Alibaba / Qwen"',
      '"speculative_decoding"',
      '"benchmark_before_after"',
      '"hypeOnlyAdoptionAllowed": False',
      '"architectureClaimsMustMatchModelMetadata": True',
      '"networkResearch": False',
      '"modelLoad": False',
      '"benchmarkRun": False',
      '"codeModification": False',
    ],
  },
  {
    file: "../backend/core/cognix/rag_planner.py",
    includes: [
      'COGNIX_RAG_PLANNER_VERSION = "cognix_rag_planner_v1"',
      'COGNIX_RAG_SOURCE_REGISTRY_VERSION = "cognix_rag_source_registry_v1"',
      "def build_rag_source_registry",
      "def build_rag_indexing_plan",
      "def build_rag_plan",
      '"sourceManifestsRequired": True',
      '"frontendDirectIndexingAllowed": False',
      '"rag_first"',
      '"hybrid"',
      '"summarize_then_cite"',
      '"fileRead": False',
      '"networkRead": False',
      '"secretRead": False',
      '"ragIndexing": False',
      '"embeddingGeneration": False',
      '"retrievalQuery": False',
      '"vectorWrite": False',
    ],
  },
  {
    file: "../backend/core/cognix/recommender.py",
    includes: [
      "latest_benchmark_run",
      "def _benchmark_signal",
      '"bestLocalModel"',
      '"Benchmark CogniX absent:',
      '"Machine calibree par benchmark local;',
    ],
  },
  {
    file: "../backend/tests/test_cognix_benchmark.py",
    includes: [
      "test_benchmark_estimates_model_fitness_without_model_side_effects",
      "test_benchmark_run_endpoint_persists_user_history_and_admin_view",
      "cognix_benchmark_v1",
      "/api/cognix/benchmark/run",
      "/api/cognix/admin/benchmark-runs",
    ],
  },
  {
    file: "../backend/tests/test_cognix_cache_manager.py",
    includes: [
      "test_cache_load_plan_selects_lru_evictions_without_loading",
      "test_cache_load_plan_endpoint_returns_audited_dry_run_plan",
      "test_preload_planner_defers_on_small_local_profile",
      "test_preload_plan_endpoint_returns_audited_dry_run_plan",
      "/api/cognix/models/cache/load-plan",
      "cache_load_plan_built",
      "/api/cognix/models/preload-plan",
      "preload_plan_built",
      "model_cache_manager_v1",
      "cognix_preload_planner_v1",
    ],
  },
  {
    file: "../backend/tests/test_cognix_strategy.py",
    includes: [
      "test_strategy_uses_latest_benchmark_run_for_recommendation",
      "test_model_recommendation_uses_latest_benchmark_run",
      "cognix_db.create_benchmark_run",
      '"bestLocalModel"',
    ],
  },
  {
    file: "../backend/tests/test_cognix_router.py",
    includes: [
      "test_context_manager_builds_bounded_context_packet",
      "test_context_plan_reserves_rag_and_caps_history",
      "test_optimization_planner_recommends_memory_safe_profile_without_reconfiguration",
      "test_optimization_plan_endpoint_logs_dry_run_decision",
      "test_optimization_capability_registry_declares_benchmark_gated_features_without_mutation",
      "test_optimization_experiment_plan_requires_benchmark_before_enablement",
      "test_optimization_capability_registry_endpoint_logs_audit_without_mutation",
      "test_optimization_experiment_plan_endpoint_blocks_enablement_until_benchmark",
      "test_runtime_adapter_registry_and_plan_select_ollama_without_side_effects",
      "test_runtime_adapter_plan_endpoint_logs_audited_dry_run",
      "test_onboarding_planner_recommends_small_local_pack_without_side_effects",
      "test_onboarding_plan_endpoint_logs_audited_dry_run",
      "test_deployment_manager_plans_enterprise_target_without_provisioning",
      "test_deployment_plan_endpoint_logs_audited_dry_run",
      "test_governance_manager_plans_university_rbac_sso_without_mutation",
      "test_governance_plan_endpoint_requires_admin_and_logs_audited_dry_run",
      "test_project_experts_plan_specialized_project_without_loading",
      "test_project_expert_plan_endpoint_uses_project_default_and_logs_audit",
      "test_model_lifecycle_plans_expert_pack_without_loading",
      "test_model_lifecycle_endpoint_logs_audited_dry_run",
      "test_thinking_status_redacts_technical_model_details",
      "test_thinking_status_endpoint_logs_audited_visible_plan",
      "test_response_reflection_scores_reliable_answer_without_model_calls",
      "test_response_reflection_flags_missing_sources_and_incomplete_answer",
      "test_response_reflection_endpoint_stores_evaluation_and_logs_audit",
      "test_response_reflection_list_endpoint_is_user_scoped",
      "test_draft_style_registry_declares_profiles_without_generation",
      "test_draft_generation_plan_prepares_variants_without_model_call",
      "test_draft_generation_plan_endpoint_logs_audit_without_generation",
      "test_response_variant_store_and_list_are_user_scoped",
      "test_debate_role_registry_declares_public_roles_without_generation",
      "test_debate_plan_prepares_bounded_rounds_without_model_call",
      "test_debate_plan_endpoint_creates_session_rounds_and_logs_audit",
      "test_debate_output_store_is_user_scoped_and_public_summary_only",
      "test_tool_discovery_capability_registry_blocks_auto_installation",
      "test_tool_discovery_plan_recommends_project_tools_without_installing",
      "test_tool_discovery_endpoint_stores_recommendations_and_ignore_is_user_scoped",
      "test_context_graph_blueprint_declares_theme_safe_graph_contract",
      "test_context_graph_snapshot_builds_nodes_edges_without_model_call",
      "test_context_graph_endpoint_stores_project_snapshot_and_audit",
      "test_skill_memory_blueprint_declares_user_control_and_no_auto_approval",
      "test_skill_memory_candidate_plan_extracts_preferences_without_writes",
      "test_skill_memory_candidate_endpoint_approves_updates_exports_and_deletes",
      "test_skill_memory_injection_plan_selects_active_relevant_memories_without_injecting",
      "test_workflow_recorder_blueprint_declares_no_execution_contract",
      "test_workflow_templates_cover_rag_fine_tuning_code_and_document",
      "test_workflow_record_endpoint_stores_steps_and_run_plan_without_execution",
      "test_workflow_update_export_and_delete_are_user_scoped_and_audited",
      "test_prompt_compression_blueprint_declares_badge_and_no_generation",
      "test_prompt_compression_plan_reduces_tokens_and_preserves_objective_terms",
      "test_prompt_compression_endpoint_stores_lists_deletes_and_audits",
      "test_intent_prediction_blueprint_declares_single_suggestion_and_no_preload",
      "test_intent_prediction_detects_code_maths_general_and_abrupt_domain_change",
      "test_intent_prediction_endpoint_stores_preload_event_without_loading",
      "test_dynamic_ui_blueprint_preserves_design_system_without_mutation",
      "test_dynamic_ui_profiles_cover_project_types_mobile_desktop_and_themes",
      "test_dynamic_ui_profile_endpoint_stores_profile_without_changing_ui",
      "test_background_agent_blueprint_requires_queue_without_worker_start",
      "test_background_agent_plan_selects_job_type_and_respects_night_mode",
      "test_background_agent_endpoint_queues_planned_job_without_starting_worker",
      "test_timeline_blueprint_declares_elegant_history_without_ui_mutation",
      "test_timeline_event_classifier_detects_core_event_types",
      "test_timeline_endpoint_stores_filters_searches_and_is_user_scoped",
      "test_memory_manager_plans_central_layers_without_writes",
      "test_memory_plan_endpoint_logs_audited_dry_run",
      "test_codex_pipeline_plans_required_gates_without_modifying_code",
      "test_codex_pipeline_endpoint_logs_audited_dry_run",
      "test_worker_queue_plans_long_running_jobs_without_enqueueing",
      "test_worker_queue_registry_declares_cloud_training_without_execution",
      "test_worker_job_spec_plan_materializes_cloud_and_rag_jobs_without_enqueueing",
      "test_worker_queue_endpoint_logs_audited_dry_run",
      "test_worker_registry_endpoint_logs_audited_dry_run",
      "test_worker_job_spec_endpoint_builds_cloud_specs_without_enqueueing",
      "test_context_pack_endpoint_combines_user_memory_and_project_instructions",
      "test_context_pack_writes_sanitized_audit_log",
      "test_audit_log_retention_prunes_old_entries",
      "test_module_registry_declares_modular_cognix_capabilities",
      "test_module_manifest_bundle_exports_declarative_contract_without_mutation",
      "test_module_manifest_endpoint_writes_sanitized_audit_log",
      "test_module_plan_endpoint_writes_sanitized_audit_log",
      "test_decision_engine_prefers_rag_before_fine_tuning_for_documents",
      "test_tool_registry_declares_permissions_and_guardrails",
      "test_tool_permission_matrix_summarizes_effective_permissions_without_execution",
      "test_tool_permission_matrix_endpoint_uses_database_permissions",
      "test_integration_manager_summarizes_connectors_without_secret_access",
      "test_integration_plan_endpoint_writes_sanitized_audit_log",
      "test_tool_plan_endpoint_allows_safe_declared_action_and_logs_audit",
      "test_tool_rate_limit_storage_blocks_after_capacity",
      "test_tool_plan_applies_rate_limit_guard",
      "test_tool_plan_blocks_disabled_connectors_before_permissions",
      "test_tool_plan_uses_database_permissions_for_connector_actions",
      "test_admin_permission_grant_and_revoke_affect_tool_planning",
      "test_orchestrator_builds_dry_run_plan_without_loading",
      "test_orchestrator_policy_blocks_tool_execution",
      "test_fine_tuning_plan_endpoint_prepares_qlora_without_training",
      "test_fine_tuning_plan_allows_ceo_cloud_training_without_local_gpu",
      "test_fine_tuning_cloud_handoff_prepares_kaggle_package_without_launch",
      "test_fine_tuning_cloud_handoff_blocks_non_ceo_cpu_without_launch",
      "test_fine_tuning_plan_defers_to_rag_for_document_objective",
      "test_rag_source_registry_declares_connectors_without_secret_or_network_access",
      "test_rag_source_registry_endpoint_logs_audited_dry_run",
      "test_rag_indexing_plan_prepares_local_sources_without_indexing",
      "test_rag_indexing_plan_blocks_sensitive_sources_without_explicit_permission",
      "test_research_watch_registry_and_plan_require_benchmark_evidence",
      "test_research_integration_endpoint_logs_audited_dry_run",
      "test_rag_plan_endpoint_prepares_hybrid_retrieval_without_indexing",
      "test_rag_plan_blocks_retrieval_when_sources_are_missing",
      "test_orchestrator_plan_endpoint_logs_dry_run_decision",
      "admin_orchestrator_logs",
      "orchestratorLogId",
      "cognix_onboarding_v1",
      "onboarding_plan_built",
      "cognix_deployment_manager_v1",
      "deployment_plan_built",
      "cognix_governance_manager_v1",
      "governance_plan_built",
      "cognix_project_experts_v1",
      "project_expert_plan_built",
      "cognix_model_lifecycle_v1",
      "model_lifecycle_plan_built",
      "cognix_thinking_status_v1",
      "thinking_status_plan_built",
      "cognix_memory_manager_v1",
      "memory_plan_built",
      "cognix_skill_memory_v1",
      "skill_memory_candidates_built",
      "skill_memory_candidate_approved",
      "skill_memory_injection_plan_built",
      "cognix_workflow_recorder_v1",
      "workflow_recording_built",
      "workflow_updated",
      "workflow_exported",
      "workflow_deleted",
      "workflow_run_plan_built",
      "cognix_prompt_compression_v1",
      "prompt_compression_plan_built",
      "prompt_compression_context_deleted",
      "cognix_intent_prediction_v1",
      "intent_prediction_built",
      "cognix_dynamic_ui_v1",
      "dynamic_ui_profile_built",
      "cognix_background_agent_v1",
      "background_agent_job_planned",
      "cognix_timeline_v1",
      "timeline_event_planned",
      "cognix_security_policy_v1",
      "cognix_preload_planner_v1",
      "cognix_fine_tuning_planner_v1",
      "cloud_qlora",
      "research_integration_plan_built",
      "cognix_research_watch_v1",
      "cognix_rag_planner_v1",
      "cognix_worker_queue_v1",
      "worker_queue_plan_built",
      "willLoadModel",
      "networkModelCall",
    ],
  },
  {
    file: "../backend/tests/test_middleware.py",
    includes: [
      "test_ceo_health_unlocks_cloud_training_without_local_gpu",
      '"cloud_training_unlocked"',
      '"training_cloud_available"',
      '"training_local_available"',
      '"cloud_ceo"',
    ],
  },
];

const scopedChecks: ScopedCheck[] = [
  {
    file: "../backend/routes/cognix.py",
    start: '@router.post("/orchestrator/plan")',
    end: "\n@router.",
    includes: [
      '"runtimeType": "dry_run"',
      "cognix_orchestrator.build_execution_plan",
      "latest_benchmark_run",
      "cognix_db.create_orchestrator_log",
      '"runtimeError": None',
    ],
    excludes: [
      "_current_model_cache_runtime()",
      "get_inference_backend",
      "get_llama_cpp_backend",
    ],
  },
];

const failures: string[] = [];

for (const check of checks) {
  const absolute = resolve(ROOT, check.file);
  const content = readFileSync(absolute, "utf8");

  for (const expected of check.includes ?? []) {
    if (!content.includes(expected)) {
      failures.push(`${check.file}: missing ${JSON.stringify(expected)}`);
    }
  }

  for (const forbidden of check.excludes ?? []) {
    if (content.includes(forbidden)) {
      failures.push(`${check.file}: forbidden ${JSON.stringify(forbidden)}`);
    }
  }
}

for (const check of scopedChecks) {
  const absolute = resolve(ROOT, check.file);
  const content = readFileSync(absolute, "utf8");
  const startIndex = content.indexOf(check.start);

  if (startIndex === -1) {
    failures.push(`${check.file}: missing scoped start ${JSON.stringify(check.start)}`);
    continue;
  }

  const endIndex = check.end ? content.indexOf(check.end, startIndex + check.start.length) : -1;
  const scopedContent = content.slice(startIndex, endIndex === -1 ? undefined : endIndex);

  for (const expected of check.includes ?? []) {
    if (!scopedContent.includes(expected)) {
      failures.push(`${check.file}: scoped block missing ${JSON.stringify(expected)}`);
    }
  }

  for (const forbidden of check.excludes ?? []) {
    if (scopedContent.includes(forbidden)) {
      failures.push(`${check.file}: scoped block contains forbidden ${JSON.stringify(forbidden)}`);
    }
  }
}

if (failures.length > 0) {
  console.error("CogniX native guard failed:");
  for (const failure of failures) {
    console.error(`- ${failure}`);
  }
  process.exit(1);
}

console.log("CogniX native guard passed.");
