// SPDX-License-Identifier: AGPL-3.0-only
// Copyright 2026-present the Unsloth AI Inc. team. All rights reserved. See /studio/LICENSE.AGPL-3.0

import { readFileSync } from "node:fs";
import { resolve } from "node:path";

const ROOT = resolve(import.meta.dirname, "..");

type Check = {
  file: string;
  includes?: string[];
  excludes?: string[];
};

type ScopedCheck = Check & {
  start: string;
  end?: string;
};

const checks: Check[] = [
  {
    file: "src/index.css",
    includes: [
      ".cognix-logo-mark",
      "transform: scale(1.04)",
      "html.dark .cognix-logo-mark",
      "invert(1) contrast(1.08)",
    ],
  },
  {
    file: "src/components/app-sidebar.tsx",
    includes: [
      'src="/cognix-logo.png"',
      "h-[31px] w-[31px]",
      "h-[24px] w-[24px]",
      "CogniX",
      "trainingAccessible",
      "cloudTrainingUnlocked",
      "showTrainingTools",
      "Local training needs an NVIDIA or AMD GPU.",
    ],
  },
  {
    file: "src/config/env.ts",
    includes: [
      "cloudTrainingUnlocked",
      "cloud_training_unlocked",
      "cloud_training_providers",
      "training_access",
      "isTrainingAccessible",
    ],
  },
  {
    file: "src/app/routes/__root.tsx",
    includes: [
      "isChatOnlyAllowed(pathname: string, trainingAccessible = false)",
      'pathname === "/studio"',
      "platform.isTrainingAccessible()",
    ],
  },
  {
    file: "../backend/main.py",
    includes: [
      '"cloud_training_unlocked"',
      '"cloud_training_providers"',
      '"training_access"',
      '"cloud_ceo"',
      "auth_storage.get_user_profile(subject)",
    ],
  },
  {
    file: "src/features/auth/components/auth-form.tsx",
    includes: [
      "cognix-auth-mode-pill",
      "Identifiant ou email",
      "Nom d'utilisateur",
      "Connexion",
      "Inscription",
    ],
    excludes: [
      "Se connecter a CogniX",
      "Se connecter à CogniX",
      "Log in to CogniX",
      "Setup your account",
      "Configurer votre compte",
    ],
  },
  {
    file: "src/features/chat/api/chat-api.ts",
    includes: [
      "CogniXContextPack",
      "CogniXExecutionPlan",
      "auditLogId",
      'CHAT_HISTORY_UPDATED_EVENT = "cognix-chat-history-updated"',
      'authFetch("/api/cognix/context/pack"',
      'authFetch("/api/cognix/orchestrator/plan"',
    ],
    excludes: [
      "unsloth-chat-history-updated",
    ],
  },
  {
    file: "src/features/chat/api/chat-adapter.ts",
    includes: [
      "buildCogniXContextPack",
      "buildLatestCogniXContextInstruction",
      "planCogniXExecution",
      "planLatestCogniXObjective",
      "willLoadModel",
      "willGenerate",
      "setLatestCogniXRoute",
    ],
    excludes: [
      "await classifyCogniXObjective",
    ],
  },
  {
    file: "src/features/chat/chat-page.tsx",
    includes: [
      "CogniX Auto",
      "latestRoute?.executionStatus",
      "Plan {latestRoute.planMode",
    ],
  },
  {
    file: "../backend/routes/cognix.py",
    includes: [
      '@router.post("/context/pack")',
      '@router.post("/benchmark/run")',
      '@router.get("/benchmark/runs")',
      '@router.get("/admin/audit-logs")',
      '@router.get("/admin/benchmark-runs")',
      '@router.get("/tools/registry")',
      '@router.get("/tools/permission-matrix")',
      '@router.post("/tools/plan")',
      '@router.get("/models/packs")',
      '@router.post("/models/lifecycle-plan")',
      '@router.post("/thinking/plan")',
      '@router.get("/memory/blueprint")',
      '@router.post("/memory/plan")',
      '@router.get("/research/watch-registry")',
      '@router.post("/research/integration-plan")',
      '@router.get("/integrations/status")',
      '@router.post("/integrations/plan")',
      '@router.get("/admin/permissions/{username}")',
      '@router.post("/admin/permissions/{username}")',
      '@router.delete("/admin/permissions/{username}/{permission_key}")',
      '@router.get("/admin/orchestrator-logs")',
      "context_pack_built",
      "rawHistoryAllowed",
      "tool_action_planned",
      "build_tool_permission_matrix",
      "integration_plan_built",
      "onboarding_plan_built",
      "deployment_plan_built",
      "governance_plan_built",
      "project_expert_plan_built",
      "model_lifecycle_plan_built",
      "thinking_status_plan_built",
      "memory_plan_built",
      "research_integration_plan_built",
      "permission_granted",
      "permission_revoked",
      "rate_limited",
      "granted_permissions = _granted_permission_keys(current_subject)",
      "cognix_db.check_rate_limit",
      "cognix_db.create_orchestrator_log",
      '@router.post("/orchestrator/plan")',
      '@router.post("/codex/pipeline-plan")',
      '@router.get("/runtime/adapters")',
      '@router.post("/runtime/plan")',
      '@router.get("/modules/registry")',
      '@router.post("/modules/plan")',
      '@router.post("/workers/plan")',
      '@router.post("/optimizations/plan")',
      '@router.post("/models/preload-plan")',
      '@router.post("/fine-tuning/plan")',
      '@router.post("/rag/plan")',
      '"orchestratorLogId"',
      '"latestBenchmark"',
      "get_latest_benchmark_run",
      '@router.post("/onboarding/plan")',
      '@router.get("/deployments/targets")',
      '@router.post("/deployments/plan")',
      '@router.get("/governance/blueprint")',
      '@router.post("/governance/plan")',
      '@router.get("/project-experts/registry")',
      '@router.post("/projects/{project_id}/expert-plan")',
      "preload_plan_built",
      "fine_tuning_plan_built",
      "rag_plan_built",
      "module_plan_built",
      "optimization_plan_built",
      "runtime_adapter_plan_built",
      "codex_pipeline_plan_built",
      "worker_queue_plan_built",
      '"runtimeType": "dry_run"',
      '"runtimeError": None',
    ],
  },
  {
    file: "../backend/storage/cognix_db.py",
    includes: [
      "CREATE TABLE IF NOT EXISTS cognix_audit_logs",
      "AUDIT_LOG_RETENTION_LIMIT",
      "def create_audit_log",
      "def list_audit_logs",
      "def prune_audit_logs",
      "def grant_user_permission",
      "def revoke_user_permission",
      "def list_user_permissions",
      "CREATE TABLE IF NOT EXISTS cognix_rate_limit_events",
      "def check_rate_limit",
      "CREATE TABLE IF NOT EXISTS cognix_orchestrator_logs",
      "def create_orchestrator_log",
      "def list_orchestrator_logs",
      "CREATE TABLE IF NOT EXISTS cognix_benchmark_runs",
      "def create_benchmark_run",
      "def list_benchmark_runs",
      "def get_latest_benchmark_run",
      "metadata_json",
    ],
  },
  {
    file: "../backend/core/cognix/benchmark.py",
    includes: [
      'COGNIX_BENCHMARK_VERSION = "cognix_benchmark_v1"',
      "def run_benchmark",
      '"estimatedTokensPerSecond"',
      '"modelFitness"',
      '"optimizationPlan"',
      '"networkCall": False',
      '"gpuStressTest": False',
    ],
  },
  {
    file: "../backend/core/cognix/decision_engine.py",
    includes: [
      'COGNIX_DECISION_ENGINE_VERSION = "cognix_decision_engine_v1"',
      "def build_task_strategy",
      '"rag_first"',
      '"guided_fine_tuning"',
      '"codex_guarded_pipeline"',
      '"toolExecution": False',
      '"fineTuningJob": False',
    ],
  },
  {
    file: "../backend/core/cognix/context_manager.py",
    includes: [
      'CONTEXT_MANAGER_VERSION = "cognix_context_manager_v1"',
      "def build_context_plan",
      '"systemInstruction"',
      '"contextPlan"',
      '"assemblyStrategy"',
      '"rawHistoryAllowed": False',
      '"never_send_raw_history"',
      '"user_memory"',
      '"project_instructions"',
      '"rag_chunks"',
      '"memoryWrite": False',
      '"ragRetrieval": False',
      '"networkModelCall": False',
    ],
  },
  {
    file: "../backend/core/cognix/memory_manager.py",
    includes: [
      'COGNIX_MEMORY_MANAGER_VERSION = "cognix_memory_manager_v1"',
      "def build_memory_blueprint",
      "def build_memory_plan",
      '"user_memory"',
      '"project_memory"',
      '"conversation_summary"',
      '"document_memory"',
      '"organization_memory"',
      '"technical_memory"',
      '"memoryIsModelIndependent": True',
      '"rawConversationHistoryDisallowedByDefault": True',
      '"frontendDirectMemoryMutationAllowed": False',
      '"rawHistoryAllowed": False',
      '"memoryScopesIsolated": True',
      '"memoryWrite": False',
      '"summaryWrite": False',
      '"documentRetrieval": False',
      '"ragIndexing": False',
      '"technicalProfileWrite": False',
      '"modelLoad": False',
      '"generation": False',
    ],
  },
  {
    file: "../backend/core/cognix/tool_registry.py",
    includes: [
      'TOOL_REGISTRY_VERSION = "cognix_tool_registry_v1"',
      "frontendDirectExecutionAllowed",
      "permissionMatrixAvailable",
      "RATE_LIMIT_POLICIES",
      "rate_limit_policy_for_key",
      "build_tool_permission_matrix",
      "permission_matrix_dry_run",
      "permissionContext",
      "guardrails",
      '"secretRead": False',
      '"permissionWrite": False',
      "requiresConfirmation",
      "auditRequired",
      "sandboxRequired",
      '"toolExecution": False',
      "def plan_tool_action",
    ],
  },
  {
    file: "../backend/core/cognix/module_registry.py",
    includes: [
      'COGNIX_MODULE_REGISTRY_VERSION = "cognix_module_registry_v1"',
      "def build_module_registry",
      "def build_module_activation_plan",
      '"cognix-onboarding"',
      '"cognix-model-lifecycle"',
      '"cognix-thinking-status"',
      '"cognix-memory-manager"',
      '"cognix-research-watch"',
      '"cognix-deployment-manager"',
      '"cloud_training_targets"',
      '"ceo_cloud_training_bypass"',
      '"technology_watch"',
      '"benchmark_gate"',
      '"tool_permission_matrix"',
      '"load_unload_planning"',
      '"technical_redaction"',
      '"central_memory_layers"',
      '"/api/cognix/models/lifecycle-plan"',
      '"/api/cognix/thinking/plan"',
      '"/api/cognix/memory/plan"',
      '"/api/cognix/research/integration-plan"',
      '"/api/cognix/tools/permission-matrix"',
      '"project_expert_routing"',
      '"/api/cognix/project-experts/registry"',
      '"sso_planning"',
      '"/api/cognix/governance/plan"',
      '"declarativeManifestRequired": True',
      '"frontendCannotSelfRegisterModules": True',
      '"moduleActivation": False',
      '"routeRegistration": False',
      '"uiMutation": False',
      '"permissionWrite": False',
    ],
  },
  {
    file: "../backend/core/cognix/integration_manager.py",
    includes: [
      'COGNIX_INTEGRATION_MANAGER_VERSION = "cognix_integration_manager_v1"',
      "def build_integration_status",
      "def build_integration_plan",
      '"secretsStayServerSide": True',
      '"directFrontendExecutionAllowed": False',
      '"integrationActivation": False',
      '"secretRead": False',
      '"toolExecution": False',
      '"networkToolCall": False',
    ],
  },
  {
    file: "../backend/core/cognix/optimization_planner.py",
    includes: [
      'COGNIX_OPTIMIZATION_PLANNER_VERSION = "cognix_optimization_planner_v1"',
      "def build_optimization_plan",
      '"quantization_profile"',
      '"prompt_cache"',
      '"kv_cache_policy"',
      '"rag_compression"',
      '"speculative_decoding"',
      '"modelReconfiguration": False',
      '"cacheMutation": False',
      '"benchmarkRun": False',
    ],
  },
  {
    file: "../backend/core/cognix/onboarding.py",
    includes: [
      'COGNIX_ONBOARDING_VERSION = "cognix_onboarding_v1"',
      "def build_onboarding_plan",
      '"hardwareSummary"',
      '"recommendedPack"',
      '"blockedModels"',
      '"firstSteps"',
      '"run_local_benchmark"',
      '"prepare_document_memory"',
      '"create_code_project"',
      '"profileWrite": False',
      '"settingsWrite": False',
      '"modelDownload": False',
      '"modelLoad": False',
      '"benchmarkRun": False',
      '"ragIndexing": False',
    ],
  },
  {
    file: "../backend/core/cognix/deployment_manager.py",
    includes: [
      'COGNIX_DEPLOYMENT_MANAGER_VERSION = "cognix_deployment_manager_v1"',
      "def build_deployment_target_registry",
      "def build_deployment_plan",
      '"on_prem_single_gpu"',
      '"on_prem_multi_gpu"',
      '"cloud_managed"',
      '"gpuScheduler"',
      '"autoscaling"',
      '"moeServing"',
      '"productionDeploymentFromPlannerAllowed": False',
      '"deployment": False',
      '"infrastructureProvisioning": False',
      '"serverStart": False',
      '"containerStart": False',
      '"dnsChange": False',
      '"secretWrite": False',
      '"networkExposure": False',
    ],
  },
  {
    file: "../backend/core/cognix/governance_manager.py",
    includes: [
      'COGNIX_GOVERNANCE_MANAGER_VERSION = "cognix_governance_manager_v1"',
      "def build_governance_blueprint",
      "def build_governance_plan",
      '"owner"',
      '"teacher"',
      '"student"',
      '"microsoft_entra_id"',
      '"google_workspace"',
      '"organizations"',
      '"rbac"',
      '"sso"',
      '"education_spaces"',
      '"class_permissions"',
      '"frontendCannotGrantRoles": True',
      '"organizationWrite": False',
      '"roleGrant": False',
      '"permissionWrite": False',
      '"ssoMutation": False',
      '"secretRead": False',
      '"secretWrite": False',
      '"directorySync": False',
      '"classroomWrite": False',
      '"policyActivation": False',
    ],
  },
  {
    file: "../backend/core/cognix/project_experts.py",
    includes: [
      'COGNIX_PROJECT_EXPERTS_VERSION = "cognix_project_experts_v1"',
      "def build_project_expert_registry",
      "def build_project_expert_plan",
      '"cognix-code"',
      '"cognix-maths"',
      '"cognix-physique"',
      '"cognix-general"',
      '"generalistVerifier"',
      '"direct_expert_for_specialized_project"',
      '"specializedProjectsPreferPrimaryExpert": True',
      '"frontendCannotLoadExpertDirectly": True',
      '"modelLoad": False',
      '"projectMutation": False',
      '"defaultModelWrite": False',
      '"cacheMutation": False',
      '"ragRetrieval": False',
      '"memoryWrite": False',
    ],
  },
  {
    file: "../backend/core/cognix/model_lifecycle.py",
    includes: [
      'COGNIX_MODEL_LIFECYCLE_VERSION = "cognix_model_lifecycle_v1"',
      "def build_model_pack_registry",
      "def build_model_lifecycle_plan",
      '"cognix-code-local"',
      '"ollama-qwen-4b-local"',
      '"glm-700b"',
      '"frontendCannotDownloadModels": True',
      '"frontendCannotLoadModelsDirectly": True',
      '"modelDownload": False',
      '"modelInstall": False',
      '"modelLoad": False',
      '"modelUnload": False',
      '"runtimeMutation": False',
      '"cacheMutation": False',
      '"networkCall": False',
      '"generation": False',
      '"settingsWrite": False',
      '"fileWrite": False',
    ],
  },
  {
    file: "../backend/core/cognix/thinking_status.py",
    includes: [
      'COGNIX_THINKING_STATUS_VERSION = "cognix_thinking_status_v1"',
      "def build_thinking_status_plan",
      '"visibleTimeline"',
      '"currentMessage"',
      '"frontendMustHideRawRoutingScores": True',
      '"frontendMustHideModelIdentifiers": True',
      '"visibleTimelineContainsModelIds": False',
      '"visibleTimelineContainsRoutingScores": False',
      '"visibleTimelineContainsRawHistory": False',
      '"modelLoad": False',
      '"generation": False',
      '"networkModelCall": False',
      '"cacheMutation": False',
      '"memoryWrite": False',
      '"ragRetrieval": False',
      '"uiMutation": False',
    ],
  },
  {
    file: "../backend/core/cognix/runtime_adapter.py",
    includes: [
      'COGNIX_RUNTIME_ADAPTER_VERSION = "cognix_runtime_adapter_v1"',
      "def build_runtime_adapter_registry",
      "def build_runtime_adapter_plan",
      '"llama.cpp"',
      '"vllm"',
      '"transformers"',
      '"frontendMustUseBackend": True',
      '"runtimeMutation": False',
      '"serverStart": False',
      '"networkModelCall": False',
    ],
  },
  {
    file: "../backend/core/cognix/codex_pipeline.py",
    includes: [
      'COGNIX_CODEX_PIPELINE_VERSION = "cognix_codex_pipeline_v1"',
      "def build_codex_pipeline_plan",
      '"create_git_branch"',
      '"modify_native_source"',
      '"run_tests"',
      '"run_build"',
      '"human_approval"',
      '"branchCreate": False',
      '"fileWrite": False',
      '"codeModification": False',
      '"merge": False',
      '"deployment": False',
    ],
  },
  {
    file: "../backend/core/cognix/worker_queue.py",
    includes: [
      'COGNIX_WORKER_QUEUE_VERSION = "cognix_worker_queue_v1"',
      "def build_worker_queue_registry",
      "def build_worker_queue_plan",
      '"rag_indexing"',
      '"fine_tuning_job"',
      '"codex_pipeline"',
      '"model_preload"',
      '"benchmark_run"',
      '"frontendDirectQueueMutationAllowed": False',
      '"jobEnqueue": False',
      '"workerStart": False',
      '"fineTuningJob": False',
      '"codeModification": False',
      '"deployment": False',
    ],
  },
  {
    file: "../backend/core/cognix/orchestrator.py",
    includes: [
      '"orchestratorVersion": "cognix_orchestrator_v1"',
      '"mode": "dry_run"',
      "latest_benchmark_run",
      "cognix_security_policy.build_execution_policy",
      "cognix_codex_pipeline.build_codex_pipeline_plan",
      "cognix_context_manager.build_context_plan",
      "cognix_optimization_planner.build_optimization_plan",
      "cognix_runtime_adapter.build_runtime_adapter_plan",
      "cognix_preload_planner.build_preload_plan",
      "cognix_project_experts.build_project_expert_plan",
      "cognix_fine_tuning_planner.build_fine_tuning_plan",
      "user_plan",
      "cognix_rag_planner.build_rag_plan",
      "cognix_worker_queue.build_worker_queue_plan",
      '"executionPolicy"',
      '"codexPipelinePlan"',
      '"workerQueuePlan"',
      '"ragPlan"',
      '"contextPlan"',
      '"optimizationPlan"',
      '"runtimeAdapterPlan"',
      '"preloadPlan"',
      '"projectExpertPlan"',
      '"fineTuningPlan"',
      '"plan_rag"',
      '"plan_codex_pipeline"',
      '"plan_context"',
      '"plan_optimizations"',
      '"select_runtime_adapter"',
      '"plan_preload"',
      '"plan_project_expert"',
      '"plan_fine_tuning"',
      '"plan_worker_queue"',
      '"ragReadyForRetrieval"',
      '"ragStrategy"',
      '"contextAssemblyStrategy"',
      '"rawHistoryAllowed"',
      '"optimizationProfile"',
      '"runtimeAdapterId"',
      '"projectExpertId"',
      '"generalistVerifierEnabled"',
      '"codexPipelineApplicable"',
      '"codexBranchName"',
      '"workerQueueRecommended"',
      '"plannedWorkerJobCount"',
      '"preloadAction"',
      '"fineTuningMethod"',
      '"automaticExecutionAllowed"',
      "cognix_decision_engine.build_task_strategy",
      '"taskStrategy"',
      '"latestBenchmark"',
      '"recommendedPath"',
      '"willLoadModel": False',
      '"willGenerate": False',
      '"networkModelCall": False',
      '"projectMutation": False',
      '"defaultModelWrite": False',
      '"jobEnqueue": False',
      '"workerStart": False',
    ],
  },
  {
    file: "../backend/core/cognix/security_policy.py",
    includes: [
      'COGNIX_SECURITY_POLICY_VERSION = "cognix_security_policy_v1"',
      "def build_execution_policy",
      '"dry_run_guarded"',
      '"automaticExecutionAllowed": False',
      '"frontendDirectModelCallAllowed": False',
      '"frontendDirectToolExecutionAllowed": False',
      '"deniedSideEffects"',
    ],
  },
  {
    file: "../backend/core/cognix/preload_planner.py",
    includes: [
      'COGNIX_PRELOAD_PLANNER_VERSION = "cognix_preload_planner_v1"',
      "def build_preload_plan",
      '"observe_only"',
      '"would_preload"',
      '"would_preload_after_lru"',
      '"defer_preload"',
      '"cacheMutation": False',
    ],
  },
  {
    file: "../backend/core/cognix/fine_tuning_planner.py",
    includes: [
      'COGNIX_FINE_TUNING_PLANNER_VERSION = "cognix_fine_tuning_planner_v1"',
      "def build_fine_tuning_plan",
      '"rag_before_fine_tuning"',
      '"guided_fine_tuning"',
      '"qlora"',
      '"cloud_qlora"',
      '"google_colab"',
      '"kaggle"',
      '"cloud_training_job"',
      '"localGpuBypassAllowed"',
      '"datasetImport": False',
      '"fineTuningJob": False',
      '"cloudTrainingJob": False',
      '"cloudCredentialRead": False',
      '"adapterWrite": False',
    ],
  },
  {
    file: "../backend/core/cognix/research_watch.py",
    includes: [
      'COGNIX_RESEARCH_WATCH_VERSION = "cognix_research_watch_v1"',
      "def build_research_watch_registry",
      "def build_research_integration_plan",
      '"DeepSeek"',
      '"Anthropic"',
      '"Google / Google DeepMind"',
      '"Sakana AI"',
      '"Alibaba / Qwen"',
      '"speculative_decoding"',
      '"benchmark_before_after"',
      '"hypeOnlyAdoptionAllowed": False',
      '"architectureClaimsMustMatchModelMetadata": True',
      '"networkResearch": False',
      '"modelLoad": False',
      '"benchmarkRun": False',
      '"codeModification": False',
    ],
  },
  {
    file: "../backend/core/cognix/rag_planner.py",
    includes: [
      'COGNIX_RAG_PLANNER_VERSION = "cognix_rag_planner_v1"',
      "def build_rag_plan",
      '"rag_first"',
      '"hybrid"',
      '"summarize_then_cite"',
      '"ragIndexing": False',
      '"embeddingGeneration": False',
      '"retrievalQuery": False',
    ],
  },
  {
    file: "../backend/core/cognix/recommender.py",
    includes: [
      "latest_benchmark_run",
      "def _benchmark_signal",
      '"bestLocalModel"',
      '"Benchmark CogniX absent:',
      '"Machine calibree par benchmark local;',
    ],
  },
  {
    file: "../backend/tests/test_cognix_benchmark.py",
    includes: [
      "test_benchmark_estimates_model_fitness_without_model_side_effects",
      "test_benchmark_run_endpoint_persists_user_history_and_admin_view",
      "cognix_benchmark_v1",
      "/api/cognix/benchmark/run",
      "/api/cognix/admin/benchmark-runs",
    ],
  },
  {
    file: "../backend/tests/test_cognix_cache_manager.py",
    includes: [
      "test_preload_planner_defers_on_small_local_profile",
      "test_preload_plan_endpoint_returns_audited_dry_run_plan",
      "/api/cognix/models/preload-plan",
      "preload_plan_built",
      "cognix_preload_planner_v1",
    ],
  },
  {
    file: "../backend/tests/test_cognix_strategy.py",
    includes: [
      "test_strategy_uses_latest_benchmark_run_for_recommendation",
      "test_model_recommendation_uses_latest_benchmark_run",
      "cognix_db.create_benchmark_run",
      '"bestLocalModel"',
    ],
  },
  {
    file: "../backend/tests/test_cognix_router.py",
    includes: [
      "test_context_manager_builds_bounded_context_packet",
      "test_context_plan_reserves_rag_and_caps_history",
      "test_optimization_planner_recommends_memory_safe_profile_without_reconfiguration",
      "test_optimization_plan_endpoint_logs_dry_run_decision",
      "test_runtime_adapter_registry_and_plan_select_ollama_without_side_effects",
      "test_runtime_adapter_plan_endpoint_logs_audited_dry_run",
      "test_onboarding_planner_recommends_small_local_pack_without_side_effects",
      "test_onboarding_plan_endpoint_logs_audited_dry_run",
      "test_deployment_manager_plans_enterprise_target_without_provisioning",
      "test_deployment_plan_endpoint_logs_audited_dry_run",
      "test_governance_manager_plans_university_rbac_sso_without_mutation",
      "test_governance_plan_endpoint_requires_admin_and_logs_audited_dry_run",
      "test_project_experts_plan_specialized_project_without_loading",
      "test_project_expert_plan_endpoint_uses_project_default_and_logs_audit",
      "test_model_lifecycle_plans_expert_pack_without_loading",
      "test_model_lifecycle_endpoint_logs_audited_dry_run",
      "test_thinking_status_redacts_technical_model_details",
      "test_thinking_status_endpoint_logs_audited_visible_plan",
      "test_memory_manager_plans_central_layers_without_writes",
      "test_memory_plan_endpoint_logs_audited_dry_run",
      "test_codex_pipeline_plans_required_gates_without_modifying_code",
      "test_codex_pipeline_endpoint_logs_audited_dry_run",
      "test_worker_queue_plans_long_running_jobs_without_enqueueing",
      "test_worker_queue_endpoint_logs_audited_dry_run",
      "test_context_pack_endpoint_combines_user_memory_and_project_instructions",
      "test_context_pack_writes_sanitized_audit_log",
      "test_audit_log_retention_prunes_old_entries",
      "test_module_registry_declares_modular_cognix_capabilities",
      "test_module_plan_endpoint_writes_sanitized_audit_log",
      "test_decision_engine_prefers_rag_before_fine_tuning_for_documents",
      "test_tool_registry_declares_permissions_and_guardrails",
      "test_tool_permission_matrix_summarizes_effective_permissions_without_execution",
      "test_tool_permission_matrix_endpoint_uses_database_permissions",
      "test_integration_manager_summarizes_connectors_without_secret_access",
      "test_integration_plan_endpoint_writes_sanitized_audit_log",
      "test_tool_plan_endpoint_allows_safe_declared_action_and_logs_audit",
      "test_tool_rate_limit_storage_blocks_after_capacity",
      "test_tool_plan_applies_rate_limit_guard",
      "test_tool_plan_blocks_disabled_connectors_before_permissions",
      "test_tool_plan_uses_database_permissions_for_connector_actions",
      "test_admin_permission_grant_and_revoke_affect_tool_planning",
      "test_orchestrator_builds_dry_run_plan_without_loading",
      "test_orchestrator_policy_blocks_tool_execution",
      "test_fine_tuning_plan_endpoint_prepares_qlora_without_training",
      "test_fine_tuning_plan_allows_ceo_cloud_training_without_local_gpu",
      "test_fine_tuning_plan_defers_to_rag_for_document_objective",
      "test_research_watch_registry_and_plan_require_benchmark_evidence",
      "test_research_integration_endpoint_logs_audited_dry_run",
      "test_rag_plan_endpoint_prepares_hybrid_retrieval_without_indexing",
      "test_rag_plan_blocks_retrieval_when_sources_are_missing",
      "test_orchestrator_plan_endpoint_logs_dry_run_decision",
      "admin_orchestrator_logs",
      "orchestratorLogId",
      "cognix_onboarding_v1",
      "onboarding_plan_built",
      "cognix_deployment_manager_v1",
      "deployment_plan_built",
      "cognix_governance_manager_v1",
      "governance_plan_built",
      "cognix_project_experts_v1",
      "project_expert_plan_built",
      "cognix_model_lifecycle_v1",
      "model_lifecycle_plan_built",
      "cognix_thinking_status_v1",
      "thinking_status_plan_built",
      "cognix_memory_manager_v1",
      "memory_plan_built",
      "cognix_security_policy_v1",
      "cognix_preload_planner_v1",
      "cognix_fine_tuning_planner_v1",
      "cloud_qlora",
      "research_integration_plan_built",
      "cognix_research_watch_v1",
      "cognix_rag_planner_v1",
      "cognix_worker_queue_v1",
      "worker_queue_plan_built",
      "willLoadModel",
      "networkModelCall",
    ],
  },
];

const scopedChecks: ScopedCheck[] = [
  {
    file: "../backend/routes/cognix.py",
    start: '@router.post("/orchestrator/plan")',
    end: "\n@router.",
    includes: [
      '"runtimeType": "dry_run"',
      "cognix_orchestrator.build_execution_plan",
      "latest_benchmark_run",
      "cognix_db.create_orchestrator_log",
      '"runtimeError": None',
    ],
    excludes: [
      "_current_model_cache_runtime()",
      "get_inference_backend",
      "get_llama_cpp_backend",
    ],
  },
];

const failures: string[] = [];

for (const check of checks) {
  const absolute = resolve(ROOT, check.file);
  const content = readFileSync(absolute, "utf8");

  for (const expected of check.includes ?? []) {
    if (!content.includes(expected)) {
      failures.push(`${check.file}: missing ${JSON.stringify(expected)}`);
    }
  }

  for (const forbidden of check.excludes ?? []) {
    if (content.includes(forbidden)) {
      failures.push(`${check.file}: forbidden ${JSON.stringify(forbidden)}`);
    }
  }
}

for (const check of scopedChecks) {
  const absolute = resolve(ROOT, check.file);
  const content = readFileSync(absolute, "utf8");
  const startIndex = content.indexOf(check.start);

  if (startIndex === -1) {
    failures.push(`${check.file}: missing scoped start ${JSON.stringify(check.start)}`);
    continue;
  }

  const endIndex = check.end ? content.indexOf(check.end, startIndex + check.start.length) : -1;
  const scopedContent = content.slice(startIndex, endIndex === -1 ? undefined : endIndex);

  for (const expected of check.includes ?? []) {
    if (!scopedContent.includes(expected)) {
      failures.push(`${check.file}: scoped block missing ${JSON.stringify(expected)}`);
    }
  }

  for (const forbidden of check.excludes ?? []) {
    if (scopedContent.includes(forbidden)) {
      failures.push(`${check.file}: scoped block contains forbidden ${JSON.stringify(forbidden)}`);
    }
  }
}

if (failures.length > 0) {
  console.error("CogniX native guard failed:");
  for (const failure of failures) {
    console.error(`- ${failure}`);
  }
  process.exit(1);
}

console.log("CogniX native guard passed.");
